# Generated by Django 4.1.2 on 2022-11-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('dueño', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('conserje', models.CharField(max_length=50)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('E', 'Entregado'), ('NE', 'No entregado')], default='NE', max_length=2)),
                ('nro_residencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.residencia')),
            ],
        ),
    ]
